# -*- coding: utf-8 -*-
"""generate_narrative.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1c1rbkxsGZ8l0oZNpn0wpX4Awj7TC-MoE
"""

import json
from datetime import datetime
from google import genai
from google.genai import types
from google.colab import userdata


# ============================================================
# HELPER FUNCTION FOR CLEAN OUTPUT
# ============================================================

def task_separator(task_number, title):
    print("\n" + "=" * 70)
    print(f"TASK {task_number} - {title}")
    print("=" * 70)


# ============================================================
# HELPER FUNCTION FOR MONTH FORMATTING
# ============================================================

def format_month(month_value: str) -> str:
    """
    Convert YYYY-MM format into a human-readable month.

    Example:
    2026-03 -> March 2026
    """

    try:
        return datetime.strptime(
            month_value,
            "%Y-%m"
        ).strftime("%B %Y")

    except ValueError:
        # If the value is already in another format,
        # return it unchanged.
        return month_value


# ============================================================
# TASK 2
# ============================================================

task_separator(2, "generate_scr_narrative")


def generate_scr_narrative(findings: dict) -> dict:

    # --------------------------------------------------------
    # Get Gemini API key from Colab Secrets
    # --------------------------------------------------------

    try:
        key = userdata.get("gemini_api")
    except Exception:
        key = None

    # --------------------------------------------------------
    # TASK 4:
    # If no API key is configured, use offline fallback.
    # --------------------------------------------------------

    if not key:
        print("No Gemini API key found. Using offline fallback.")
        return generate_scr_narrative_offline(findings)

    # Create Gemini client
    client = genai.Client(api_key=key)

    # --------------------------------------------------------
    # Convert month dynamically
    # --------------------------------------------------------

    true_peak_month = format_month(
        findings["true_peak_month"]["month"]
    )

    outlier_month = format_month(
        findings["outlier_inflated_month"]["month"]
    )

    # --------------------------------------------------------
    # System instruction
    # --------------------------------------------------------

    system_instruction = """
You are a senior data analyst writing for Mamaearth's regional ops and
finance heads.

Write the business narrative using exactly three labeled sections:

Situation
Complication
Resolution

Requirements:
- Every number in the output must come from the supplied findings.
- Every number must appear with the same value as provided in the findings.
- Do not invent, estimate, calculate, or derive any new statistics.
- Do not introduce numerical facts that are not present in the findings.
- Use only the information provided in the findings.
- Keep the narrative professional, concise, and business-focused.
- Clearly explain the business meaning of the verified findings.
- The output must contain exactly the three sections:
  Situation, Complication, Resolution.
- When reporting a month stored as YYYY-MM, write it using the
  human-readable month name and year, such as "March 2026".
- The verified peak month and its revenue must be stated together.
"""

    # --------------------------------------------------------
    # Build the user prompt dynamically from findings
    # --------------------------------------------------------

    user_prompt = f"""
Write an SCR business narrative using the following verified findings.

Cleaned total revenue:
₹{findings['cleaned_total_revenue_inr']:.2f}

Raw total revenue:
₹{findings['raw_total_revenue_inr']:.2f}

Duplicate reconciliation delta:
₹{findings['duplicate_reconciliation_delta_inr']:.2f}

Return rate by payment method:
COD: {findings['return_rate_by_payment']['COD']:.1f}%
CARD: {findings['return_rate_by_payment']['CARD']:.1f}%
UPI: {findings['return_rate_by_payment']['UPI']:.1f}%

Highest-risk segment:
Payment method: {findings['highest_risk_segment']['payment_method']}
City tier: {findings['highest_risk_segment']['city_tier']}
Return rate: {findings['highest_risk_segment']['return_rate_pct']:.1f}%

True peak month:
Month: {true_peak_month}
Revenue: ₹{findings['true_peak_month']['revenue_inr']:.2f}

Outlier-inflated month:
Month: {outlier_month}
Apparent revenue: ₹{findings['outlier_inflated_month']['apparent_revenue_inr']:.2f}
Corrected revenue: ₹{findings['outlier_inflated_month']['corrected_revenue_inr']:.2f}

Important:
- Use the month name and year for the true peak month.
- State the true peak month and its revenue together.
- Do not change or round any supplied numerical value.
- Do not add any statistics that are not supplied.

Use exactly these three sections:

Situation

Complication

Resolution
"""

    # ========================================================
    # TASK 3 - Parameter locking and error handling
    # ========================================================

    try:

        # Temperature is 0.0 because this is a factual business
        # report, not creative writing. We want deterministic output.

        response = client.models.generate_content(
            model="gemini-3.5-flash-lite",
            contents=user_prompt,
            config=types.GenerateContentConfig(
                system_instruction=system_instruction,

                # Deterministic output
                temperature=0.0,

                # Explicitly above the required minimum
                max_output_tokens=300,

                # Timeout is 30 seconds = 30000 milliseconds.
                # This is above the required 10-second minimum.
                http_options=types.HttpOptions(
                    timeout=30000
                )
            )
        )

        # Get token usage if available
        tokens = None

        if response.usage_metadata is not None:
            tokens = response.usage_metadata.total_token_count

        # Return structured success response
        return {
            "status": "success",
            "narrative": response.text,
            "tokens": tokens
        }

    except Exception as err:

        # Never allow the caller to receive a raw exception.
        # Return a structured error response instead.

        return {
            "status": "error",
            "narrative": None,
            "message": str(err)
        }


# ============================================================
# TASK 4 - OFFLINE FALLBACK
# ============================================================

def generate_scr_narrative_offline(findings: dict) -> dict:
    """
    Fully deterministic offline fallback.

    This function:
    - Does not use Gemini
    - Does not use an API key
    - Does not make a network call
    - Uses only values from findings
    """

    # Convert months dynamically
    true_peak_month = format_month(
        findings["true_peak_month"]["month"]
    )

    outlier_month = format_month(
        findings["outlier_inflated_month"]["month"]
    )

    narrative = f"""
Situation

Mamaearth's cleaned total revenue is ₹{findings['cleaned_total_revenue_inr']:.2f},
compared with the raw total revenue of ₹{findings['raw_total_revenue_inr']:.2f}.
The duplicate reconciliation delta is ₹{findings['duplicate_reconciliation_delta_inr']:.2f}.
Return rates vary by payment method: COD is
{findings['return_rate_by_payment']['COD']:.1f}%,
CARD is {findings['return_rate_by_payment']['CARD']:.1f}%, and
UPI is {findings['return_rate_by_payment']['UPI']:.1f}%.

Complication

The highest-risk segment is
{findings['highest_risk_segment']['payment_method']}
in city tier {findings['highest_risk_segment']['city_tier']},
with a {findings['highest_risk_segment']['return_rate_pct']:.1f}% return rate.

The apparent peak in {outlier_month} is
₹{findings['outlier_inflated_month']['apparent_revenue_inr']:.2f},
but after accounting for outliers its corrected revenue is
₹{findings['outlier_inflated_month']['corrected_revenue_inr']:.2f}.

Resolution

The verified revenue peak is {true_peak_month} at
₹{findings['true_peak_month']['revenue_inr']:.2f}.

Regional operations and finance teams should use the cleaned revenue figures,
focus return investigation on the identified high-risk payment and city-tier
segment, and use the outlier-corrected monthly trend for business decisions.
"""

    return {
        "status": "success",
        "narrative": narrative.strip(),
        "tokens": None
    }


# ============================================================
# TASK 5 - NUMERIC ACCURACY CHECKER
# ============================================================

def check_numeric_accuracy(narrative: str) -> bool:
    """
    Checks whether all five required figures are present
    in the narrative.

    Commas are removed before checking so that:
    97,358.30 and 97358.30 are treated as equivalent.
    """

    # Normalize commas and convert to lowercase
    normalized = narrative.replace(",", "").lower()

    # Required figures
    checks = [
        (
            "Cleaned total revenue",
            "97358.30"
        ),
        (
            "COD return rate",
            "44.4"
        ),
        (
            "COD + Tier-2 return rate",
            "54.5"
        ),
        (
            "Duplicate reconciliation delta",
            "2501.90"
        )
    ]

    all_passed = True

    # --------------------------------------------------------
    # Check first four figures using assert
    # --------------------------------------------------------

    for label, figure in checks:

        try:
            assert figure in normalized

            print(
                f"PASS - {label}: {figure}"
            )

        except AssertionError:

            print(
                f"FAIL - {label}: {figure}"
            )

            all_passed = False

    # --------------------------------------------------------
    # Check March + 20318.90 using assert
    # --------------------------------------------------------

    try:

        assert "march" in normalized

        assert (
            "20318.90" in normalized
            or "20318.9" in normalized
        )

        print(
            "PASS - True peak month: March + 20318.90"
        )

    except AssertionError:

        print(
            "FAIL - True peak month: March + 20318.90"
        )

        all_passed = False

    # --------------------------------------------------------
    # Final result
    # --------------------------------------------------------

    if all_passed:

        print("\nTASK 5: PASS")

    else:

        print("\nTASK 5: FAIL")

    return all_passed


# ============================================================
# MAIN PROGRAM
# ============================================================

if __name__ == "__main__":

    # --------------------------------------------------------
    # Load findings
    # --------------------------------------------------------

    with open(
        "findings.json",
        "r",
        encoding="utf-8"
    ) as f:

        findings = json.load(f)

    # --------------------------------------------------------
    # Generate SCR narrative
    # --------------------------------------------------------

    result = generate_scr_narrative(findings)

    # --------------------------------------------------------
    # If Gemini failed, use offline fallback
    # --------------------------------------------------------

    if result["status"] == "error":

        print("\nGemini API failed.")
        print("Using offline fallback.")
        print("Error:", result["message"])

        result = generate_scr_narrative_offline(
            findings
        )

    # ========================================================
    # DISPLAY SCR
    # ========================================================

    if result["status"] == "success":

        print("\n" + "=" * 70)
        print("SCR NARRATIVE")
        print("=" * 70)

        print(result["narrative"])

        print("\nStatus:", result["status"])
        print("Tokens:", result["tokens"])

        # ====================================================
        # TASK 5
        # ====================================================

        print("\n" + "=" * 70)
        print("TASK 5 - NUMERIC ACCURACY CHECK")
        print("=" * 70)

        check_numeric_accuracy(
            result["narrative"]
        )


        # ====================================================
        # SAVE SAMPLE OUTPUT WITH CHECKS
        # ====================================================

        normalized = result["narrative"].replace(",", "")

        checks = [
            ("Cleaned total revenue", "97358.30"),
            ("COD return rate", "44.4"),
            ("COD + Tier-2 return rate", "54.5"),
            ("Duplicate reconciliation delta", "2501.90"),
            ("True peak month", "march")
        ]

        all_passed = True

        with open(
            "sample_output.txt",
            "w",
            encoding="utf-8"
        ) as f:

            f.write("SCR NARRATIVE\n")
            f.write("=" * 70 + "\n\n")
            f.write(result["narrative"])

            f.write("\n\n")
            f.write("=" * 70 + "\n")
            f.write("TASK 5 - NUMERIC ACCURACY CHECK\n")
            f.write("=" * 70 + "\n")

            for label, value in checks:

                if value.lower() in normalized.lower():
                    f.write(
                        f"\nPASS - {label}: {value}"
                    )

                else:
                    f.write(
                        f"\nFAIL - {label}: {value}"
                    )
                    all_passed = False

            # Check March + 20318.90 together
            if (
                "march" in normalized.lower()
                and (
                    "20318.90" in normalized
                    or "20318.9" in normalized
                )
            ):
                f.write(
                    "\nPASS - True peak revenue: 20318.90"
                )

            else:
                f.write(
                    "\nFAIL - True peak revenue: 20318.90"
                )
                all_passed = False

            f.write("\n\nTASK 5: ")

            f.write(
                "PASS"
                if all_passed
                else "FAIL"
            )

        print(
            "\nSample output saved to sample_output.txt"
        )


        # ====================================================
        # CHECK SAVED SAMPLE
        # ====================================================

        with open(
            "sample_output.txt",
            "r",
            encoding="utf-8"
        ) as f:

            saved_narrative = f.read()

        print(
            "\n" + "=" * 70
        )
        print(
            "CHECKING SAVED sample_output.txt"
        )
        print(
            "=" * 70
        )

        check_numeric_accuracy(
            saved_narrative
        )


    else:

        print("Generation failed.")
        print(
            "Status:",
            result["status"]
        )
        print(
            "Error:",
            result["message"]
        )