# -*- coding: utf-8 -*-
"""clean_and_eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1PKUPJ6JkKO5TNTnhIyeqKi2q8nNsG6bt
"""

import numpy as np
import pandas as pd


# ============================================================
# HELPER FUNCTION FOR CLEAN OUTPUT
# ============================================================

def task_separator(task_number, title):
    print("\n" + "=" * 70)
    print(f"TASK {task_number} - {title}")
    print("=" * 70)


# ============================================================
# TASK 1
# ============================================================

task_separator(1, "Load Data")

orders = pd.read_csv('orders.csv')
products = pd.read_csv('products.csv')
customers = pd.read_csv('customers.csv')

print(f"Orders shape: {orders.shape}")


# ============================================================
# TASK 2
# ============================================================

task_separator(2, "Clean Payment Method")

print(f"Before fix:\n{orders['payment_method'].unique()}")

orders['payment_method'] = (
    orders['payment_method']
    .str.strip()
    .str.upper()
)

print(f"\nAfter fix:\n{orders['payment_method'].unique()}")

print(
    f"\nAfter fix value counts:\n"
    f"{orders['payment_method'].value_counts()}"
)


# ============================================================
# TASK 3
# ============================================================

task_separator(3, "Remove Duplicate Orders")

duplicate_cols = [
    'customer_id',
    'product_id',
    'order_date',
    'quantity',
    'discount_pct',
    'payment_method',
    'rating',
    'returned'
]

# Detect duplicate rows
detect_duplicates = orders.duplicated(
    subset=duplicate_cols,
    keep='first'
)

# Check number of duplicates
print(
    f"Number of duplicates: "
    f"{detect_duplicates.sum()}"
)

# Print order_id of duplicate rows
print(
    f"\nDropped order_id:\n"
    f"{orders.loc[detect_duplicates, 'order_id'].tolist()}"
)

# Remove duplicates
orders_clean = orders.drop_duplicates(
    subset=duplicate_cols,
    keep='first'
).copy()

# Check final shape
print(
    f"\nOrders shape after removing duplicates: "
    f"{orders_clean.shape}"
)


# ============================================================
# TASK 4
# ============================================================

task_separator(4, "Impute Missing Values")

# Fill missing discount_pct with 0
orders_clean['discount_pct'] = (
    orders_clean['discount_pct'].fillna(0)
)

# Calculate median rating before imputing
rating_median = orders_clean['rating'].median()

print(f"Median rating: {rating_median}")

# Fill missing rating with median
orders_clean['rating'] = (
    orders_clean['rating'].fillna(rating_median)
)

# Check missing values after imputation
print(
    "\nMissing values after imputation:"
)

print(
    orders_clean[['discount_pct', 'rating']]
    .isnull()
    .sum()
)


# ============================================================
# TASK 5
# ============================================================

task_separator(5, "Merge and Reconcile Against Part 1")

# Merge cleaned orders with products
orders_merged = orders_clean.merge(
    products[['product_id', 'price']],
    on='product_id',
    how='left'
)

# Merge with customers
orders_merged = orders_merged.merge(
    customers,
    on='customer_id',
    how='left'
)

# Calculate order_value
orders_merged['order_value'] = (
    orders_merged['quantity']
    * orders_merged['price']
    * (1 - orders_merged['discount_pct'] / 100)
)

# Total order value after cleaning
cleaned_total = orders_merged['order_value'].sum()

print(
    f"Total order value after cleaning: "
    f"₹{cleaned_total:.2f}"
)


# Calculate order_value of the 5 dropped duplicate rows
dropped_orders = orders.loc[detect_duplicates].copy()

dropped_orders = dropped_orders.merge(
    products[['product_id', 'price']],
    on='product_id',
    how='left'
)

dropped_orders['order_value'] = (
    dropped_orders['quantity']
    * dropped_orders['price']
    * (1 - dropped_orders['discount_pct'] / 100)
)

dropped_total = dropped_orders['order_value'].sum()

print(
    f"Order value of 5 dropped duplicates: "
    f"₹{dropped_total:.2f}"
)


# Reconciliation
print(
    f"\nReconciliation:\n"
    f"The cleaned order value total is "
    f"₹{cleaned_total:.2f}, which is "
    f"₹2501.90 lower than the Part 1 raw total "
    f"of ₹99860.20.\n"
    f"This exact difference is attributable to the "
    f"5 duplicate rows removed in Task 3, whose "
    f"combined order_value is ₹{dropped_total:.2f}.\n"
    f"The discount_pct and rating imputations do not "
    f"change this difference because rating is not used "
    f"in the order_value calculation."
)


# ============================================================
# TASK 6
# ============================================================

task_separator(6, "IQR Outlier Detection on Quantity")

# Calculate Q1 and Q3
Q1 = orders_merged['quantity'].quantile(0.25)
Q3 = orders_merged['quantity'].quantile(0.75)

# Calculate IQR
IQR = Q3 - Q1

# Calculate lower and upper bounds
lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print(f"Q1: {Q1}")
print(f"Q3: {Q3}")
print(f"IQR: {IQR}")
print(f"Lower bound: {lower}")
print(f"Upper bound: {upper}")


# Flag outliers
orders_merged['is_outlier'] = (
    (orders_merged['quantity'] < lower) |
    (orders_merged['quantity'] > upper)
)

# Show outlier rows
outliers = orders_merged[
    orders_merged['is_outlier']
]

print(f"\nNumber of outliers: {len(outliers)}")

print(
    f"\nOutliers List:\n"
    f"{outliers[['order_id', 'quantity', 'is_outlier']]}"
)


# ============================================================
# TASK 7
# ============================================================

task_separator(7, "Return Rate by Payment Method")

print(
    "Hypothesis: COD has a higher return rate than CARD and UPI."
)

return_rate = (
    orders_merged
    .groupby('payment_method')['returned']
    .agg(['count', 'mean'])
)

print("\nReturn rate by payment method:")
print(return_rate)


# Convert mean to percentage
return_rate['return_rate_pct'] = (
    return_rate['mean'] * 100
)

print("\nReturn rates (%):")
print(
    return_rate['return_rate_pct'].round(1)
)

print(
    "\nHypothesis: Confirmed, COD has a higher return rate than CARD and UPI."
)


# ============================================================
# TASK 8
# ============================================================

task_separator(8, "Multi-Level Segmentation")

segment_return_rate = (
    orders_merged
    .groupby(
        ['payment_method', 'city_tier']
    )['returned']
    .agg(['count', 'mean'])
)

segment_return_rate['return_rate_pct'] = (
    segment_return_rate['mean'] * 100
)

print(
    "Return rate by payment method and city tier:"
)

print(
    segment_return_rate.round(
        {'return_rate_pct': 1}
    )
)


# Show COD segmentation
print("\nCOD segmentation:")

cod_segments = segment_return_rate.loc['COD']

print(
    cod_segments.round(
        {'return_rate_pct': 1}
    )
)


# Find COD Tier-1 and Tier-2 rows automatically
print("\nCOD segment details:")

for tier, row in cod_segments.iterrows():
    print(
        f"COD + Tier-{tier} cities: "
        f"{int(row['count'])} orders "
        f"at {row['return_rate_pct']:.1f}% return rate"
    )


# Find highest-risk segment
highest_risk = (
    segment_return_rate['return_rate_pct']
    .idxmax()
)

highest_rate = (
    segment_return_rate['return_rate_pct']
    .max()
)

print(
    f"\nHighest-risk segment: "
    f"{highest_risk[0]} + "
    f"Tier-{highest_risk[1]} cities "
    f"at {highest_rate:.1f}%"
)


print(
    "\nCOD risk is not uniform across tiers: "
    "Tier-1 has 32 COD orders at 37.5%, whereas "
    "Tier-2 has 22 COD orders at 54.5%.\n"
    "This shows that a single blended COD return rate "
    "can hide where the real problem is concentrated."
)


# ============================================================
# TASK 9
# ============================================================

task_separator(9, "Correlation Analysis")

# Select required columns
corr_cols = [
    'rating',
    'returned',
    'discount_pct',
    'quantity'
]

# Calculate correlation matrix
corr_matrix = orders_merged[
    corr_cols
].corr()

print("Correlation Matrix:")
print(
    corr_matrix.round(2)
)


# Function to classify correlation strength
def correlation_strength(r):
    r = abs(r)

    if r < 0.2:
        return "negligible"
    elif r < 0.4:
        return "weak"
    elif r < 0.7:
        return "moderate"
    else:
        return "strong"


# Print every pairwise correlation
print(
    "\nPairwise correlation strength:"
)

for i in range(len(corr_cols)):
    for j in range(i + 1, len(corr_cols)):

        col1 = corr_cols[i]
        col2 = corr_cols[j]

        r = corr_matrix.loc[col1, col2]

        strength = correlation_strength(r)

        print(
            f"{col1} vs {col2}: "
            f"r = {r:.2f} → {strength}"
        )


# Hypothesis
discount_return_corr = (
    corr_matrix.loc[
        'discount_pct',
        'returned'
    ]
)

print(
    f"\nHypothesis: Higher discounts reduce returns "
    f"→ Busted "
    f"(correlation = {discount_return_corr:.2f})"
)

# Task 10 - Outlier-corrected time series

task_separator(10, "Outlier-corrected time series")

# Convert order_date to datetime
orders_merged['order_date'] = pd.to_datetime(orders_merged['order_date'], format='%d-%m-%Y')

# Extract year-month
orders_merged['year_month'] = orders_merged['order_date'].dt.to_period('M')

# 1. Monthly total including outliers
monthly_with_outliers = (
    orders_merged
    .groupby('year_month')['order_value']
    .sum()
)

print("Monthly order value INCLUDING outliers:")
print(monthly_with_outliers.round(2))


# 2. Monthly total excluding outliers
monthly_without_outliers = (
    orders_merged[~orders_merged['is_outlier']]
    .groupby('year_month')['order_value']
    .sum()
)

print("\nMonthly order value EXCLUDING outliers:")
print(monthly_without_outliers.round())


# Print the highest month in each series
highest_month_with = monthly_with_outliers.idxmax()
highest_value_with = monthly_with_outliers.max()

highest_month_without = monthly_without_outliers.idxmax()
highest_value_without = monthly_without_outliers.max()

print(
    f"\nHighest month including outliers: "
    f"{highest_month_with} = ₹{highest_value_with:.2f}"
)

print(
    f"Highest month excluding outliers: "
    f"{highest_month_without} = ₹{highest_value_without:.2f}"
)


# Required interpretation
print(
    "\nInterpretation: January's apparent lead is an artifact of the "
    "two bulk orders landing in January: O0011 on 2026-01-28 and "
    "O0098 on 2026-01-10. Once these two outlier orders are excluded, "
    "March is the genuine peak month. This shows why the outliers were "
    "flagged in Task 6 before performing the time-series analysis."
)

"""# Findings.json"""

# ============================================================
# NARRATOR - TASK 1
# Generate findings.json from verified Part 1 + Part 2 data
# ============================================================

import json
import os

print("\n" + "=" * 70)
print("NARRATOR - TASK 1: EXPORT VERIFIED FINDINGS")
print("=" * 70)


# ------------------------------------------------------------
# 1. Raw total revenue
# ------------------------------------------------------------

# Calculate raw order value using original orders
raw_orders = orders.merge(
    products[['product_id', 'price']],
    on='product_id',
    how='left'
)

raw_orders['order_value'] = (
    raw_orders['quantity']
    * raw_orders['price']
    * (1 - raw_orders['discount_pct'].fillna(0) / 100)
)

raw_total_revenue = raw_orders['order_value'].sum()


# ------------------------------------------------------------
# 2. Cleaned total revenue
# ------------------------------------------------------------

# Already calculated earlier in Task 5
cleaned_total_revenue = orders_merged['order_value'].sum()


# ------------------------------------------------------------
# 3. Duplicate reconciliation delta
# ------------------------------------------------------------

duplicate_reconciliation_delta = (
    raw_total_revenue - cleaned_total_revenue
)


# ------------------------------------------------------------
# 4. Return rate by payment method
# ------------------------------------------------------------

return_rates = (
    orders_merged
    .groupby('payment_method')['returned']
    .mean()
    .mul(100)
)


# ------------------------------------------------------------
# 5. Highest-risk payment + city-tier segment
# ------------------------------------------------------------

highest_risk_idx = (
    segment_return_rate['return_rate_pct']
    .idxmax()
)

highest_risk_rate = (
    segment_return_rate['return_rate_pct']
    .max()
)


# ------------------------------------------------------------
# 6. Monthly revenue including outliers
# ------------------------------------------------------------

orders_merged['order_date'] = pd.to_datetime(
    orders_merged['order_date'],format='%d-%m-%Y'
)

orders_merged['year_month'] = (
    orders_merged['order_date']
    .dt.to_period('M')
)

monthly_revenue_all = (
    orders_merged
    .groupby('year_month')['order_value']
    .sum()
)


# ------------------------------------------------------------
# 7. Monthly revenue excluding outliers
# ------------------------------------------------------------

monthly_revenue_corrected = (
    orders_merged[
        ~orders_merged['is_outlier']
    ]
    .groupby('year_month')['order_value']
    .sum()
)


# True peak month after removing outliers
true_peak_month = (
    monthly_revenue_corrected.idxmax()
)

true_peak_revenue = (
    monthly_revenue_corrected.max()
)


# Outlier-inflated month
outlier_inflated_month = (
    monthly_revenue_all.idxmax()
)

apparent_revenue = (
    monthly_revenue_all.max()
)

corrected_revenue = (
    monthly_revenue_corrected.loc[
        outlier_inflated_month
    ]
)


# ------------------------------------------------------------
# 8. Create findings dictionary
# ------------------------------------------------------------

findings = {
    "cleaned_total_revenue_inr": round(
        cleaned_total_revenue, 2
    ),

    "raw_total_revenue_inr": round(
        raw_total_revenue
    ),

    "duplicate_reconciliation_delta_inr": round(
        duplicate_reconciliation_delta, 2
    ),

    "return_rate_by_payment": {
        "COD": round(return_rates["COD"], 1),
        "CARD": round(return_rates["CARD"], 1),
        "UPI": round(return_rates["UPI"], 1)
    },

    "highest_risk_segment": {
        "payment_method": highest_risk_idx[0],
        "city_tier": int(highest_risk_idx[1]),
        "return_rate_pct": round(
            highest_risk_rate, 1
        )
    },

    "true_peak_month": {
        "month": str(true_peak_month),
        "revenue_inr": round(
            true_peak_revenue, 2
        )
    },

    "outlier_inflated_month": {
        "month": str(outlier_inflated_month),
        "apparent_revenue_inr": round(
            apparent_revenue, 2
        ),
        "corrected_revenue_inr":
            corrected_revenue
    }
}




# ------------------------------------------------------------
# 9. Write findings.json
# ------------------------------------------------------------

findings_path = (
    'findings.json'
)

with open(
    findings_path,
    'w',
    encoding='utf-8'
) as f:

    json.dump(
        findings,
        f,
        indent=2
    )


# ------------------------------------------------------------
# 10. Validate generated JSON
# ------------------------------------------------------------

print("\nfindings.json:")
print(
    json.dumps(
        findings,
        indent=2
    )
)

print(
    "\n✓ findings.json generated successfully."
)