import pandas as pd
import matplotlib.pyplot as plt
import os

# Create visualization folder if it doesn't exist
os.makedirs('visualizations', exist_ok=True)

# Load cleaned and merged data generated by clean_and_eda.py
orders_merged = pd.read_csv('orders_merged_clean.csv')

# ============================================================
# Visualization 1 - Return rate by payment method
# ============================================================

return_rate = (
    orders_merged
    .groupby('payment_method')['returned']
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

plt.figure(figsize=(8, 5))

bars = plt.bar(
    return_rate.index,
    return_rate.values
)

# Add exact percentage labels
for bar, value in zip(bars, return_rate.values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f'{value:.1f}%',
        ha='center',
        va='bottom'
    )

plt.xlabel('Payment Method')
plt.ylabel('Return Rate (%)')
plt.title('COD Returns at 44.4% — 3x Card')
plt.tight_layout()

plt.savefig(
    'visualizations/return_rate_by_payment.png',
    dpi=300
)
plt.show()
plt.close()


# ============================================================
# Visualization 2 - Outlier-corrected monthly revenue trend
# ============================================================

orders_merged['order_date'] = pd.to_datetime(
    orders_merged['order_date'],
    format='%Y-%m-%d'
)


orders_merged['year_month'] = (
    orders_merged['order_date']
    .dt.to_period('M')
)

monthly_revenue = (
    orders_merged[
        ~orders_merged['is_outlier']
    ]
    .groupby('year_month')['order_value']
    .sum()
)

# Find actual peak month
peak_month = monthly_revenue.idxmax()
peak_value = monthly_revenue.max()

plt.figure(figsize=(9, 5))

plt.plot(
    monthly_revenue.index.astype(str),
    monthly_revenue.values,
    marker='o'
)

plt.xlabel('Month')
plt.ylabel('Revenue (₹)')

plt.title(
    f'Monthly Revenue Trend — Peak: {peak_month} '
    f'(₹{peak_value:.2f})'
)

plt.xticks(rotation=45)

plt.tight_layout()

plt.savefig(
    'monthly_revenue_trend.png',
    dpi=300,
    bbox_inches='tight'
)
plt.show()
plt.close()

print("Visualizations created successfully.")
print("Saved: visualizations/return_rate_by_payment.png")
print("Saved: visualizations/monthly_revenue_trend.png")

# ==============================
# VALIDATE GRAPH DATA
# ==============================

print("\n========== VALIDATION ==========")

# 1. Validate return rate by payment method
actual_return_rate = (
    orders_merged
    .groupby('payment_method')['returned']
    .agg(['count', 'sum', 'mean'])
)

actual_return_rate['return_rate_%'] = (
    actual_return_rate['mean'] * 100
)

actual_return_rate = actual_return_rate.sort_values(
    'return_rate_%',
    ascending=False
)

print("\nReturn Rate by Payment Method:")
print(actual_return_rate[['count', 'sum', 'return_rate_%']].round(1))


# 2. Validate monthly revenue
orders_merged['order_date'] = pd.to_datetime(
    orders_merged['order_date']
)

orders_merged['year_month'] = (
    orders_merged['order_date'].dt.to_period('M')
)

actual_monthly_revenue = (
    orders_merged[~orders_merged['is_outlier']]
    .groupby('year_month')['order_value']
    .sum()
)

print("\nMonthly Revenue (Outliers Excluded):")
print(actual_monthly_revenue.round(2))

print(
    f"\nPeak Month: {actual_monthly_revenue.idxmax()}"
)

print(
    f"Peak Revenue: ₹{actual_monthly_revenue.max():.2f}"
)
