# -*- coding: utf-8 -*-
"""visualize.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hNCEGpskgyON2nakWa-eg8yWcgDaIUxT
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


# ============================================================
# LOAD RAW DATA
# ============================================================

orders = pd.read_csv('orders.csv')
products = pd.read_csv('products.csv')
customers = pd.read_csv('customers.csv')


# ============================================================
# CLEAN PAYMENT METHOD
# ============================================================

orders['payment_method'] = (
    orders['payment_method']
    .str.strip()
    .str.upper()
)


# ============================================================
# REMOVE DUPLICATES
# ============================================================

duplicate_cols = [
    'customer_id',
    'product_id',
    'order_date',
    'quantity',
    'discount_pct',
    'payment_method',
    'rating',
    'returned'
]

orders_clean = orders.drop_duplicates(
    subset=duplicate_cols,
    keep='first'
).copy()


# ============================================================
# IMPUTE MISSING VALUES
# ============================================================

orders_clean['discount_pct'] = (
    orders_clean['discount_pct'].fillna(0)
)

rating_median = orders_clean['rating'].median()

orders_clean['rating'] = (
    orders_clean['rating'].fillna(rating_median)
)


# ============================================================
# MERGE DATA
# ============================================================

orders_merged = orders_clean.merge(
    products[['product_id', 'price']],
    on='product_id',
    how='left'
)

orders_merged = orders_merged.merge(
    customers,
    on='customer_id',
    how='left'
)


# ============================================================
# CALCULATE ORDER VALUE
# ============================================================

orders_merged['order_value'] = (
    orders_merged['quantity']
    * orders_merged['price']
    * (1 - orders_merged['discount_pct'] / 100)
)


# ============================================================
# IDENTIFY QUANTITY OUTLIERS
# ============================================================

Q1 = orders_merged['quantity'].quantile(0.25)
Q3 = orders_merged['quantity'].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

orders_merged['is_outlier'] = (
    (orders_merged['quantity'] < lower)
    | (orders_merged['quantity'] > upper)
)


# ============================================================
# CREATE VISUALIZATIONS FOLDER
# ============================================================

os.makedirs('visualizations', exist_ok=True)


# ============================================================
# TASK 11.1
# RETURN RATE BY PAYMENT METHOD
# ============================================================

return_rate = (
    orders_merged
    .groupby('payment_method')['returned']
    .mean()
    .mul(100)
    .sort_values(ascending=False)
)

plt.figure(figsize=(8, 5))

bars = plt.bar(
    return_rate.index,
    return_rate.values
)

# Add exact percentage labels
for bar, rate in zip(bars, return_rate.values):
    plt.text(
        bar.get_x() + bar.get_width() / 2,
        bar.get_height(),
        f'{rate:.1f}%',
        ha='center',
        va='bottom'
    )

card_rate = return_rate['CARD']
cod_rate = return_rate['COD']

ratio = cod_rate / card_rate

plt.title(
    f'COD Returns at {cod_rate:.1f}% — {ratio:.0f}x Card'
)

plt.xlabel('Payment Method')
plt.ylabel('Return Rate (%)')

plt.tight_layout()

plt.savefig(
    'return_rate_by_payment.png',
    dpi=300,
    bbox_inches='tight'
)
plt.show()
plt.close()


# ============================================================
# TASK 11.2
# OUTLIER-CORRECTED MONTHLY REVENUE
# ============================================================

orders_merged['order_date'] = pd.to_datetime(
    orders_merged['order_date'],
    format='%d-%m-%Y'

)

orders_merged['year_month'] = (
    orders_merged['order_date']
    .dt.to_period('M')
)

monthly_revenue = (
    orders_merged[
        ~orders_merged['is_outlier']
    ]
    .groupby('year_month')['order_value']
    .sum()
)

# Find actual peak month
peak_month = monthly_revenue.idxmax()
peak_value = monthly_revenue.max()

plt.figure(figsize=(9, 5))

plt.plot(
    monthly_revenue.index.astype(str),
    monthly_revenue.values,
    marker='o'
)

plt.xlabel('Month')
plt.ylabel('Revenue (₹)')

plt.title(
    f'Monthly Revenue Trend — Peak: {peak_month} '
    f'(₹{peak_value:.2f})'
)

plt.xticks(rotation=45)

plt.tight_layout()

plt.savefig(
    'monthly_revenue_trend.png',
    dpi=300,
    bbox_inches='tight'
)
plt.show()
plt.close()


# ============================================================
# CONFIRM OUTPUT
# ============================================================

print(
    'Created: return_rate_by_payment.png'
)

print(
    'Created: monthly_revenue_trend.png'
)

print(
    f'Actual peak month: {peak_month} '
    f'with revenue ₹{peak_value:.2f}'
)

# ==============================
# VALIDATE GRAPH DATA
# ==============================

print("\n========== VALIDATION ==========")

# 1. Validate return rate by payment method
actual_return_rate = (
    orders_merged
    .groupby('payment_method')['returned']
    .agg(['count', 'sum', 'mean'])
)

actual_return_rate['return_rate_%'] = (
    actual_return_rate['mean'] * 100
)

actual_return_rate = actual_return_rate.sort_values(
    'return_rate_%',
    ascending=False
)

print("\nReturn Rate by Payment Method:")
print(actual_return_rate[['count', 'sum', 'return_rate_%']].round(1))


# 2. Validate monthly revenue
orders_merged['order_date'] = pd.to_datetime(
    orders_merged['order_date']
)

orders_merged['year_month'] = (
    orders_merged['order_date'].dt.to_period('M')
)

actual_monthly_revenue = (
    orders_merged[~orders_merged['is_outlier']]
    .groupby('year_month')['order_value']
    .sum()
)

print("\nMonthly Revenue (Outliers Excluded):")
print(actual_monthly_revenue.round(2))

print(
    f"\nPeak Month: {actual_monthly_revenue.idxmax()}"
)

print(
    f"Peak Revenue: ₹{actual_monthly_revenue.max():.2f}"
)